### ISSUE TITLE
Change a bit? 

### ISSUE THREAD

**Issue by ColinTNMP** [IntenseBattle2/IB2-Music#1]
I love the idea of a central folder for different assets--I was actually thinking of doing the same thing. But what about having it for ALL assets, and just have one folder for music? It would be like one folder for music, one for code, etc.
It's just a suggestion. I'm completely ok with it if you want to just keep it how it is and discard this idea, @Zachman9841

**Comment by Zachman9841** [comment]
Yeah that's a good idea! @ColinTNMP Do whatever you need to do and change whatever you need to change.

**Comment by ColinTNMP** [comment]
@Zachman9841 Alright, I'll make the changes and see how you like them.

**Comment by Zachman9841** [comment]
I like the new changes already and I also merged the project. @ColinTNMP
